// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTTk4jYgyX3kBn383NsHbwjy18qSwUHFs',
    appId: '1:1039728172723:web:9dc05c706a072372b59ac6',
    messagingSenderId: '1039728172723',
    projectId: 'smart-agriculture-monito-dfd68',
    authDomain: 'smart-agriculture-monito-dfd68.firebaseapp.com',
    storageBucket: 'smart-agriculture-monito-dfd68.appspot.com',
    measurementId: 'G-EVMRR4HS1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTT3IRFZcMZyv2VuRDoet6GFsxXQKquF8',
    appId: '1:1039728172723:android:ac5ca7515d980a5cb59ac6',
    messagingSenderId: '1039728172723',
    projectId: 'smart-agriculture-monito-dfd68',
    storageBucket: 'smart-agriculture-monito-dfd68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH0WGTKBxvl33nY2CifW52ozQS0fOCZHE',
    appId: '1:1039728172723:ios:ef005f0774fa7c16b59ac6',
    messagingSenderId: '1039728172723',
    projectId: 'smart-agriculture-monito-dfd68',
    storageBucket: 'smart-agriculture-monito-dfd68.appspot.com',
    iosBundleId: 'com.example.smartAgricultureMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH0WGTKBxvl33nY2CifW52ozQS0fOCZHE',
    appId: '1:1039728172723:ios:ef005f0774fa7c16b59ac6',
    messagingSenderId: '1039728172723',
    projectId: 'smart-agriculture-monito-dfd68',
    storageBucket: 'smart-agriculture-monito-dfd68.appspot.com',
    iosBundleId: 'com.example.smartAgricultureMonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTTk4jYgyX3kBn383NsHbwjy18qSwUHFs',
    appId: '1:1039728172723:web:9f70aded4fdf913cb59ac6',
    messagingSenderId: '1039728172723',
    projectId: 'smart-agriculture-monito-dfd68',
    authDomain: 'smart-agriculture-monito-dfd68.firebaseapp.com',
    storageBucket: 'smart-agriculture-monito-dfd68.appspot.com',
    measurementId: 'G-Z0CCRMKYE0',
  );
}
